import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Facilities & Property Management KSI Reports
        </h1>

        <p className={styles.description}>
          Get started by selecting a shop from the options below
        </p>

        <div className={styles.grid}>
          <h2 className={styles.card}>
            <Link href="/shops/bldgmaint">
              <a>Bldg Maint</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/construction">
              <a>Construction</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/electrical">
              <a>Electrical</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/energymgmt">
              <a>Energy Mgmt</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/housing">
              <a>Housing</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/landscaping">
              <a>Landscaping</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/locksmith">
              <a>Locksmith</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/plumbing">
              <a>Plumbing</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/systems">
              <a>Systems</a>
            </Link>
          </h2>

          <h2 className={styles.card}>
            <Link href="/shops/zone">
              <a>Zone</a>
            </Link>
          </h2>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
